apiVersion: v2
appVersion: "1.0"
description: A Helm chart for wa-case-event-handler App
name: wa-case-event-handler
home: https://github.com/hmcts/wa-case-event-handler
version: 0.0.40
maintainers:
  - name: HMCTS wa team
dependencies:
  - name: java
    version: 5.2.0
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
